export const ALL_METRICS_CONFIG = {
  placas_industrial: [
    {
      key: "placas",
      item: "Placas",
      label: "Placas a Instaladar",
      unit: "un.",
      reportKey: "placas_instaladas",
      targetKey: "placas_a_instalar",
      actionPhrase: "Se instalaron",
    },
    {
      key: "estructura",
      item: "Estructura",
      label: "Estructura a Instalar",
      unit: "un.",
      reportKey: "estructura_instalada",
      targetKey: "estructura_a_instalar",
      actionPhrase: "Se montaron",
    },
    {
      key: "cable",
      item: "Cable",
      label: "Cable Tendido",
      unit: "mts",
      reportKey: "metros_cable_tendido",
      targetKey: "metros_cable",
      actionPhrase: "Se tendieron",
    },
    {
      key: "canalizacion",
      item: "Canalización",
      label: "Canalización Realizada",
      unit: "mts",
      reportKey: "metros_canalizacion_realizada",
      targetKey: "metros_canalizacion",
      actionPhrase: "Se realizaron",
    },
  ],
  hincado: [
    {
      key: "hincas",
      item: "Hincas",
      label: "Hincas Realizadas",
      unit: "un.",
      reportKey: "hincas_realizadas",
      targetKey: "hincas",
      actionPhrase: "Se realizaron",
    },
    {
      key: "predrilling",
      item: "Predrilling",
      label: "Predrilling Realizado",
      unit: "un.",
      reportKey: "predrilling_realizado",
      targetKey: "predrilling",
      actionPhrase: "Se realizaron",
    },
    {
      key: "reparto",
      item: "Hincas",
      label: "Reparto de Hincas",
      unit: "un.",
      reportKey: "reparto_hincas",
      targetKey: "hincas_repartir",
      actionPhrase: "Se repartieron",
    },
  ],
  seguridad_altura: [
    {
      key: "valla",
      item: "Valla Perimetral",
      label: "Valla Perimetral",
      unit: "mts",
      reportKey: "valla_perimetral_instalada",
      targetKey: "valla_perimetral",
      actionPhrase: "Se instalaron",
    },
    {
      key: "escaleras",
      item: "Escaleras",
      label: "Escaleras Instaladas",
      unit: "un.",
      reportKey: "escaleras_instaladas",
      targetKey: "escaleras_instaladas",
      actionPhrase: "Se instalaron",
    },
    {
      key: "lineas",
      item: "Líneas de Vida",
      label: "Líneas de Vida",
      unit: "mts",
      reportKey: "lineas_de_vida_instaladas",
      targetKey: "lineas_vida",
      actionPhrase: "Se instalaron",
    },
  ],
};
